### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by sc1341**
-- Added more user agents to spoof in the constants.py file by incorporating a random.choice() method on a list of random user agents

-- Deleted extra commented-out code

-- Deleted Extra Variables that were unused

-- Formatted the argparse parser into its own method which returns the args

-- Made the username an actual argument (using --username or -u) for consistency purposes

-- Added Doc Strings for functions

 -- replaced `return "done"` with `return True` to make the statement more clear

-- Organized import statements to be in alphabetical order

-- Added .DS_Store and __pycache__ to the .gitignore

-- Complete restructure of the argparse parsing. It is now much more clean and easier to read. It is also less error prone.

-- Added a .gitignore for the vscoscrape directory

-- The multiple user feature now works. `python3 vscoscrape.py -m user1 user2 user3`. This runs both the journal and the photo scrape on the user

### CODE REVIEW

**Comment by sc1341** [comment]
Another note -- Change the import statement on the constant import form `import constants` to `from . import constants` if you want to build it to the command line using setup.py. I was testing it as I was making changes which is why the import statement is changed.

**Comment by mvabdi** [comment]
I'll do a couple tests then merge more than likely, thanks for the contribution!

**Comment by sc1341** [comment]
Hi there! Sorry for the late response -- what are your thoughts on the updates so far?

**Comment by mvabdi** [comment]
Decided to use your parser, but keep the rest of it as is due to the last PR I merged. Also -m is used just for text files where you write the username sequentially down a list instead of a lot of usernames next to each other. I did appreciate the comments.

I wrote this in HS self taught, and so had no idea you should probably be using booleans instead of returning "done". It was kinda funny to see you updating it and adding the booleans in.

**Pull request merged**
